-- create table
CREATE TABLE STUDENT( ID INT PRIMARY KEY,NAME VARCHAR(20),SCORE NUMERIC );

--ADD INDEX
CREATE INDEX INDX ON  STUDENT(SCORE);

SHOW CREATE TABLE STUDENT;
DROP INDEX INDX ON STUDENT;
SHOW CREATE TABLE STUDENT;